# ===================================================================
# Standard Spring Boot properties.
# Full reference is available at:
# http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
# ===================================================================

management:

spring:
  application:
    name: client-service

server:
  port: 8081

rest:
  base-url: http://localhost
